image:
  cert-manager.io/cluster-issuer: letsencrypt-prod
  tag: "{{ TAG }}"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,If-None-Match,x-blackfire-query,apikey"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: veralanaservicos.anadata.nasajon.com.br
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
    - secretName: veralanaservicos-anadata-tls
      hosts:
        - veralanaservicos.anadata.nasajon.com.br

configMap:
  create: true
  name: "veralana-ana-data"
  data:
    django_debug: "false"
    django_allowed_host: veralanaservicos.anadata.nasajon.com.br
    database_name_nasajon: nasajon_11578336000152
    database_host_nasajon: "nasajon-amb06-bd-01.skyone.app"
    database_port_nasajon: "5432"
    database_user_nasajon: ana_data      
    allowed_username: ana@nasajon.com.br
    keycloak_client_id: ana-data
    keycloak_url: https://auth.nasajon.com.br/auth
    sentry_env: VERALANA

secret:
  create: true
  name: "veralana-ana-data"
  data: 
    keycloak_realm: master

affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node_group
          operator: In
          values:
          - ng-ana