name: App Build

on:
  push:
    branches:
      - teste
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          ref: main

    - name: Set Environment Variable
      uses: ./.github/actions/set-env.yaml

    - name: "Testando condicional"
      run: |
        echo $MY_ENV_VAR