name: App Build

on:
  push:
    branches:
      - teste
  workflow_dispatch:
    
env:
  APP_NAME: ana-data
  ARGO_PROJECT: ana-data
  CHART_FOLDER: charts/projeto-ana
  HELM_REPO: git@github.com:NasajonSRE/helm.git
  BRANCH_NAME: development
  HARBOR_PROJECT: ana

jobs:

  init:

    runs-on: ubuntu-latest
    outputs:
      CLIENTES: ${{ env.nomes }}
      CLUSTER: ${{ env.cluster }}
      VERSION: ${{ env.version }}
      VAULT_URL: ${{ env.vault_url }}
      VALUES_FILE: ${{ env.values_file }}
      FILES: ${{ env.files }}
      NAMES: ${{ env.nomes }}

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{github.base_ref}}

    - name: Set variables
      id: setvars
      run: |

        if [[ "${{github.base_ref}}" == "teste" || "${{github.ref}}" == "refs/heads/teste" ]]; then
          echo "cluster=nasajon-prod" >> "$GITHUB_ENV"
          echo "version=$BUILD" >> "$GITHUB_ENV"
          echo "vault_url=safe.nasajon.app" >> "$GITHUB_ENV"
          echo "values_file=-values.yaml" >> "$GITHUB_ENV"
          file_names=$(find ci -name "*-values.yaml" -type f -printf "%f\n" | grep -vE "qa-values.yaml|dev-values.yaml")
          file_list=()
          for file in $file_names; do
            name="${file%-values.yaml}"
            file_list+=("$name")
          done
          echo "nomes=${file_list[@]}" >> "$GITHUB_ENV"
        fi

  build:

    runs-on: ubuntu-latest
    needs: init

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{github.base_ref}}

    - name: Render Values in Helm git repo 
      env:
        NAMES: ${{ needs.init.outputs.NAMES }}
        CLUSTER: ${{ env.cluster }}
      run: | 
        echo Create temporary folder to clone the repo into...
        TEMP_FOLDER="$(mktemp -d)" 
        for client in $NAMES; do
          echo " "
          cp ci/${client}-values.yaml ${TEMP_FOLDER}/${client}-values.yaml
          echo "Update Helm values with new image tag"
          sed -i "s/{{ TAG }}/$GITHUB_DOCKERTAG/g" ${TEMP_FOLDER}/${client}-values.yaml
          cat ${TEMP_FOLDER}/${client}-values.yaml
        done
        echo "done"