name: App Build

on:
  push:
    branches:
      - teste
  workflow_dispatch:
    
env:
  TESTE: ${{ github.ref == 'refs/heads/main' && 'IMMA MAIN' || github.ref == 'refs/heads/test' && 'IMMA TESTIN' || github.ref == 'refs/heads/branch' && 'IMMA USEFUL' }}
  teste2: ${{ if eq(github.ref, 'refs/heads/main') }}value-for-branch-a${{ else if eq(github.ref, 'refs/heads/test') }}value-for-branch-b${{ else if eq(github.ref, 'refs/heads/branch') }}value-for-branch-c${{ else }}value-for-other-branches${{ endif }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          ref: main

    - name: "Testando condicional"
      run: |
        echo $TESTE
        echo $teste2