name: "Agora e o certo guigui"

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

env:
  SPRINT: 2306

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      BRANCH: ${{ env.branch }}
    #   VERSION: ${{ steps.setvars.outputs.version }}
    #   VAULT_URL: ${{ steps.setvars.outputs.vault_url }}

    steps:
      - name: Set variables
        id: setvars
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

  print:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Sets env vars for environment
        run: |
          echo "BRANCH=$(echo ${{needs.init.outputs.BRANCH}})" >> $GITHUB_ENV

      # - name: Sets Vault Key
      #   run: |
      #     if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/production" ]]; then
      #       echo "TESTE=${{ secrets.TESTE }}" >> "$GITHUB_ENV"
      #     fi

      #     if [[ "${{github.base_ref}}" == "development" || "${{github.ref}}" == "refs/heads/development" ]]; then
      #       echo "TESTE=${{ secrets.TESTE_DEV }}" >> "$GITHUB_ENV"
      #     fi

      - name: Print
        run: |
          echo $BRANCH