name: App Build

on:
  push:
    branches:
      - teste
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          ref: teste

    - name: Set Environment Variables
      id: set_env_vars
      run: |
        export $(cat teste.env)

    - name: "Testando condicional"
      run: |
        echo $MY_ENV_VAR